Repository git1uv/server, pull requests merged in 2024-08, with the labels that each got.

#25 :sparkles: [Feat] 스웨거 설정
  build.gradle
  src/main/java/com/simter/config/SwaggerConfig.java
Labels: ✨ Feature

#26 ✨[Feat] 종이비행기 조회, 등록 API 구현
  .DS_Store
  config/checkstyle.xml
  docker-compose.yml
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/simter/GlobalExceptionHandler.java
  src/main/java/com/simter/domain/airplane/controller/.gitkeep
  src/main/java/com/simter/domain/airplane/controller/AirplaneController.java
  src/main/java/com/simter/domain/airplane/controller/dto/.gitkeep
  src/main/java/com/simter/domain/airplane/converter/.gitkeep
  src/main/java/com/simter/domain/airplane/dto/AirplaneGetResponseDto.java
  src/main/java/com/simter/domain/airplane/dto/AirplanePostRequestDto.java
  src/main/java/com/simter/domain/airplane/dto/AirplanePostResponseDto.java
  src/main/java/com/simter/domain/airplane/exception/AirplaneGetException.java
  src/main/java/com/simter/domain/airplane/exception/AirplanePostException.java
  src/main/java/com/simter/domain/airplane/repository/.gitkeep
  src/main/java/com/simter/domain/airplane/repository/AirplaneRepository.java
  src/main/java/com/simter/domain/airplane/service/.gitkeep
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
Labels: ✨ Feature

#32 [Feat] : API 응답 통일 & 에러 핸들링
  build.gradle
  src/main/java/com/simter/GlobalExceptionHandler.java
  src/main/java/com/simter/apiPayload/ApiResponse.java
  src/main/java/com/simter/apiPayload/code/BaseCode.java
  src/main/java/com/simter/apiPayload/code/ReasonDTO.java
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/simter/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/simter/apiPayload/exception/GeneralException.java
  src/main/java/com/simter/apiPayload/exception/handler/ErrorHandler.java
  src/main/java/com/simter/config/WebSecurityConfig.java
  src/main/java/com/simter/domain/airplane/controller/AirplaneController.java
  src/main/java/com/simter/domain/airplane/converter/AirplaneConverter.java
  src/main/java/com/simter/domain/airplane/dto/AirplaneGetResponseDto.java
  src/main/java/com/simter/domain/airplane/exception/AirplaneGetException.java
  src/main/java/com/simter/domain/airplane/exception/AirplanePostException.java
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
Labels: ✨ Feature

#33 :recycle: [Recycle] : Airplane 수정
  src/main/java/com/simter/domain/airplane/controller/AirplaneController.java
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
  src/main/java/com/simter/domain/member/repository/MemberRepository.java
Labels: 🔨 Refactor

#34 (작업 중) [Feat] : 편지 조회 API
  src/main/java/com/simter/domain/airplane/controller/AirplaneController.java
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
  src/main/java/com/simter/domain/mail/controller/.gitkeep
  src/main/java/com/simter/domain/mail/controller/MailController.java
  src/main/java/com/simter/domain/mail/controller/dto/.gitkeep
  src/main/java/com/simter/domain/mail/converter/.gitkeep
  src/main/java/com/simter/domain/mail/converter/MailConverter.java
  src/main/java/com/simter/domain/mail/dto/MailDeleteResponseDto.java
  src/main/java/com/simter/domain/mail/dto/MailGetResponseDto.java
  src/main/java/com/simter/domain/mail/dto/MailStarRequestDto.java
  src/main/java/com/simter/domain/mail/dto/MailStarResponseDto.java
  src/main/java/com/simter/domain/mail/entity/Mail.java
  src/main/java/com/simter/domain/mail/repository/.gitkeep
  src/main/java/com/simter/domain/mail/repository/MailRepository.java
  src/main/java/com/simter/domain/mail/service/.gitkeep
  src/main/java/com/simter/domain/mail/service/MailService.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/java/com/simter/domain/member/repository/MemberRepository.java
Labels: ✨ Feature

#36 [Feat] 편지 삭제, 즐겨찾기 추가 API 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/mail/controller/MailController.java
  src/main/java/com/simter/domain/mail/dto/MailStarRequestDto.java
  src/main/java/com/simter/domain/mail/dto/MailStarResponseDto.java
  src/main/java/com/simter/domain/mail/entity/Mail.java
  src/main/java/com/simter/domain/mail/repository/MailRepository.java
  src/main/java/com/simter/domain/mail/service/MailService.java
Labels: ✨ Feature

#37 [Feat] 일반 로그인 기능 구현
  .DS_Store
  .gitignore
  build.gradle
  docker-compose.yml
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/simter/SimterApplication.java
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/config/JwtAuthenticationFilter.java
  src/main/java/com/simter/config/JwtTokenProvider.java
  src/main/java/com/simter/config/OAuth2SuccessHandler.java
  src/main/java/com/simter/config/SwaggerConfig.java
  src/main/java/com/simter/config/WebSecurityConfig.java
  src/main/java/com/simter/config/checkstyle.xml
  src/main/java/com/simter/domain/member/controller/MemberController.java
  src/main/java/com/simter/domain/member/controller/OAuthController.java
  src/main/java/com/simter/domain/member/converter/MemberConverter.java
  src/main/java/com/simter/domain/member/converter/TokenConverter.java
  src/main/java/com/simter/domain/member/dto/JwtTokenDto.java
  src/main/java/com/simter/domain/member/dto/MemberRequestDto.java
  src/main/java/com/simter/domain/member/dto/MemberResponseDto.java
  src/main/java/com/simter/domain/member/dto/TokenReissueRequestDto.java
  src/main/java/com/simter/domain/member/dto/TokenResponse.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/java/com/simter/domain/member/exception/InvalidEmailFormatException.java
  src/main/java/com/simter/domain/member/exception/InvalidNicknameFormatException.java
  src/main/java/com/simter/domain/member/exception/InvalidPasswordFormatException.java
  src/main/java/com/simter/domain/member/repository/MemberRepository.java
  src/main/java/com/simter/domain/member/service/KakaoOAuthService.java
  src/main/java/com/simter/domain/member/service/MemberService.java
  src/main/java/com/simter/domain/member/service/OAuth2UserService.java
  src/main/java/com/simter/domain/member/service/UserDetailsServiceImpl.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
  src/test/java/com/simter/domain/member/controller/MemberControllerTest.java
Labels: ✨ Feature

#45 [Feat] Default 챗봇 변경 API
  src/main/java/com/simter/domain/chatbot/controller/.gitkeep
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/controller/dto/.gitkeep
  src/main/java/com/simter/domain/chatbot/converter/.gitkeep
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/converter/dummy.txt
  src/main/java/com/simter/domain/chatbot/dto/DefaultChatbotRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/GetChatbotTypeResponseDto.java
  src/main/java/com/simter/domain/chatbot/repository/.gitkeep
  src/main/java/com/simter/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/com/simter/domain/chatbot/service/.gitkeep
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/member/entity/Member.java
Labels: ✨ Feature

#47 [Feat] 메인, 설정 api 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/member/controller/MemberController.java
  src/main/java/com/simter/domain/member/dto/MainDto.java
  src/main/java/com/simter/domain/member/dto/MemberRequestDto.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/java/com/simter/domain/member/service/MemberService.java
Labels: ✨ Feature

#50 [Fix] 토큰 핸들링 로직 변경
  src/main/java/com/simter/config/JwtAuthenticationFilter.java
  src/main/java/com/simter/config/JwtTokenProvider.java
  src/main/java/com/simter/domain/member/controller/MemberController.java
  src/main/java/com/simter/domain/member/converter/TokenConverter.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/java/com/simter/domain/member/service/KakaoOAuthService.java
  src/main/java/com/simter/domain/member/service/MemberService.java
Labels: ✨ Feature, 🐞 Bug

#51 [Feat] 사용할 챗봇 선택, 챗봇 세션 생성 API 구현
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/dto/SelectChatbotRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/SelectChatbotResponseDto.java
  src/main/java/com/simter/domain/chatbot/entity/CounselingLog.java
  src/main/java/com/simter/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/test/java/com/simter/domain/chatbot/controller/ChatbotControllerTest.java
Labels: ✨ Feature

#53 [Docs] 스웨거 토큰 설정 추가
  src/main/java/com/simter/config/SwaggerConfig.java
Labels: 📃 Docs

#56 (구현 중) [Feat] 상담일지 가져오기 API 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/GetCounselingLogResponseDto.java
  src/main/java/com/simter/domain/chatbot/entity/CounselingLog.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/mail/dto/MailGetResponseDto.java
  src/main/java/com/simter/domain/mail/entity/Mail.java
Labels: ✨ Feature

#58 Feature/#55
  docker-compose.yml
  src/main/java/com/simter/domain/calendar/controller/.gitkeep
  src/main/java/com/simter/domain/calendar/controller/CalendarsController.java
  src/main/java/com/simter/domain/calendar/controller/dto/.gitkeep
  src/main/java/com/simter/domain/calendar/converter/.gitkeep
  src/main/java/com/simter/domain/calendar/converter/CalendarsConverter.java
  src/main/java/com/simter/domain/calendar/dto/CalendarsResponseDto.java
  src/main/java/com/simter/domain/calendar/entity/Calendars.java
  src/main/java/com/simter/domain/calendar/repository/.gitkeep
  src/main/java/com/simter/domain/calendar/repository/CalendarsRepository.java
  src/main/java/com/simter/domain/calendar/service/.gitkeep
  src/main/java/com/simter/domain/calendar/service/CalendarsService.java
  src/main/java/com/simter/domain/mail/controller/MailController.java
  src/main/java/com/simter/domain/mail/entity/Mail.java
  src/main/java/com/simter/domain/mail/repository/MailRepository.java
  src/main/java/com/simter/domain/mail/service/MailService.java
  src/main/java/com/simter/domain/member/service/MemberService.java
Labels: 🐞 Bug
