Repository git1uv/server, pull requests merged in 2024-09, with the labels that each got.

#60 [Feat] Claude API 구현 챗봇 대화 API 구현
  build.gradle
  src/main/java/com/simter/SimterApplication.java
  src/main/java/com/simter/config/AwsConfig.java
  src/main/java/com/simter/config/WebClientConfig.java
  src/main/java/com/simter/config/WebConfig.java
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/ClaudeRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/ClaudeResponseDto.java
  src/main/java/com/simter/domain/chatbot/entity/ChatbotMessage.java
  src/main/java/com/simter/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#61 [Feat] 달력 API 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/calendar/controller/CalendarsController.java
  src/main/java/com/simter/domain/calendar/converter/CalendarsConverter.java
  src/main/java/com/simter/domain/calendar/dto/CalendarsRequestDto.java
  src/main/java/com/simter/domain/calendar/dto/CalendarsResponseDto.java
  src/main/java/com/simter/domain/calendar/entity/Calendars.java
  src/main/java/com/simter/domain/calendar/repository/CalendarsRepository.java
  src/main/java/com/simter/domain/calendar/service/CalendarsService.java
  src/main/java/com/simter/domain/chatbot/entity/CounselingLog.java
  src/main/java/com/simter/domain/chatbot/repository/CalendarCounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/member/converter/MemberConverter.java
  src/main/java/com/simter/domain/member/service/OAuth2UserService.java
  src/main/java/com/simter/domain/solution/entity/Solution.java
  src/main/java/com/simter/domain/solution/repository/.gitkeep
  src/main/java/com/simter/domain/solution/repository/CalendarSolutionRepository.java
  src/main/java/com/simter/domain/solution/repository/SolutionRepository.java
Labels: ✨ Feature

#65 [Feat] 챗봇 대화 종료, 상담일지 생성 API 구현
  src/main/java/com/simter/apiPayload/ApiResponse.java
  src/main/java/com/simter/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/simter/domain/calendar/converter/CalendarsConverter.java
  src/main/java/com/simter/domain/calendar/service/CalendarsService.java
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/ChatbotRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/ChatbotResponseDto.java
  src/main/java/com/simter/domain/chatbot/dto/ClaudeResponseDto.java
  src/main/java/com/simter/domain/chatbot/dto/CounselingResponseDto.java
  src/main/java/com/simter/domain/chatbot/dto/DefaultChatbotRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/GetChatbotTypeResponseDto.java
  src/main/java/com/simter/domain/chatbot/dto/GetCounselingLogResponseDto.java
  src/main/java/com/simter/domain/chatbot/dto/SelectChatbotRequestDto.java
  src/main/java/com/simter/domain/chatbot/dto/SelectChatbotResponseDto.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarSolution.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarSolutionId.java
  src/main/java/com/simter/domain/chatbot/entity/CounselingLog.java
  src/main/java/com/simter/domain/chatbot/entity/Solution.java
  src/main/java/com/simter/domain/chatbot/repository/CalendarCounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CalendarSolutionRepository.java
  src/main/java/com/simter/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/repository/SolutionRepository.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
  src/main/java/com/simter/domain/solution/controller/.gitkeep
  src/main/java/com/simter/domain/solution/controller/dto/.gitkeep
  src/main/java/com/simter/domain/solution/converter/.gitkeep
  src/main/java/com/simter/domain/solution/repository/CalendarSolutionRepository.java
  src/main/java/com/simter/domain/solution/repository/SolutionRepository.java
  src/main/java/com/simter/domain/solution/service/.gitkeep
  src/test/java/com/simter/domain/chatbot/controller/ChatbotControllerTest.java
Labels: ✨ Feature

#68 [Feat] 상담일지 조회 API 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/CounselingResponseDto.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
Labels: ✨ Feature

#71 [Feat] 편지 생성 기능 구현
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
  src/main/java/com/simter/domain/mail/controller/MailController.java
  src/main/java/com/simter/domain/mail/converter/MailConverter.java
  src/main/java/com/simter/domain/mail/entity/Mail.java
  src/main/java/com/simter/domain/mail/entity/UserMailbox.java
  src/main/java/com/simter/domain/mail/repository/MailRepository.java
  src/main/java/com/simter/domain/mail/service/MailService.java
  src/main/java/com/simter/domain/member/entity/Member.java
  src/main/java/com/simter/domain/member/service/MemberService.java
  src/main/java/com/simter/domain/member/service/UserDetailsServiceImpl.java
Labels: ✨ Feature

#72 [Chore] 코드 리팩토링
  src/main/java/com/simter/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/simter/domain/airplane/controller/AirplaneController.java
  src/main/java/com/simter/domain/airplane/converter/AirplaneConverter.java
  src/main/java/com/simter/domain/airplane/dto/AirplaneGetResponseDto.java
  src/main/java/com/simter/domain/airplane/dto/AirplanePostRequestDto.java
  src/main/java/com/simter/domain/airplane/repository/AirplaneRepository.java
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
  src/main/java/com/simter/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/simter/domain/chatbot/service/ChatbotService.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
  src/main/java/com/simter/domain/mail/controller/MailController.java
  src/test/java/com/simter/domain/chatbot/controller/ChatbotControllerTest.java
Labels: ♻️ Chore

#73 :sparkles: [Chore] Calendars, CounselingLog, Solution 매핑테이블 삭제
  src/main/java/com/simter/domain/calendar/converter/CalendarsConverter.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarCounselingLog.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarCounselingLogId.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarSolution.java
  src/main/java/com/simter/domain/chatbot/entity/CalendarSolutionId.java
  src/main/java/com/simter/domain/chatbot/entity/CounselingLog.java
  src/main/java/com/simter/domain/chatbot/repository/CalendarCounselingLogRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CalendarSolutionRepository.java
  src/main/java/com/simter/domain/chatbot/repository/CounselingLogRepository.java
Labels: ✨ Feature

#77 [Feat] 챗봇 종료 시 달력 생성 구현
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/config/SwaggerConfig.java
  src/main/java/com/simter/domain/calendar/converter/CalendarsConverter.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/CounselingResponseDto.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
Labels: ✨ Feature, ♻️ Chore

#78 [CI] Create gradle.yml
  .github/workflows/gradle.yml
Labels: 🌏 CI/CD

#81 [Feat]dotenv 관련 코드 제거
  Dockerfile
  build.gradle
  src/main/java/com/simter/SimterApplication.java
  src/main/java/com/simter/config/JwtTokenProvider.java
  src/main/java/com/simter/config/SwaggerConfig.java
  src/main/java/com/simter/config/WebConfig.java
  src/main/java/com/simter/config/WebSecurityConfig.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
  src/main/java/com/simter/domain/member/service/KakaoOAuthService.java
  src/main/java/com/simter/domain/member/service/OAuth2UserService.java
Labels: ✨ Feature

#86 [Chore] 상담일지 조회 API 챗봇타입 추가
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/CounselingResponseDto.java
Labels: ♻️ Chore

#88 [Feat] Claude 챗봇 프롬프트 수정
  src/main/java/com/simter/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/simter/domain/airplane/service/AirplaneService.java
  src/main/java/com/simter/domain/calendar/repository/CalendarsRepository.java
  src/main/java/com/simter/domain/chatbot/converter/ChatbotConverter.java
  src/main/java/com/simter/domain/chatbot/dto/ClaudeResponseDto.java
  src/main/java/com/simter/domain/chatbot/entity/ChatbotMessage.java
  src/main/java/com/simter/domain/chatbot/service/ClaudeAPIService.java
Labels: ✨ Feature, ♻️ Chore
